# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Tests - Pytest

on:
  push:
    branches: [ master, rahil, arka ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install flask flask_cors numpy spacy nltk language-tool-python sentence-transformers torch==1.8.1+cpu --find-links https://download.pytorch.org/whl/torch_stable.html
        python -m nltk.downloader stopwords && python3 -m nltk.downloader punkt && python3 -m nltk.downloader wordnet
        python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('bert-base-nli-mean-tokens')"
        python -c "import language_tool_python; language_tool_python.LanguageTool('en-US')"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
